-- Fix facilities table schema
ALTER TABLE facilities 
ADD COLUMN IF NOT EXISTS year_built INTEGER,
ADD COLUMN IF NOT EXISTS rooms INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS active_issues INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS occupancy_rate INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS description TEXT;

-- Ensure all facilities columns exist
ALTER TABLE facilities 
ADD COLUMN IF NOT EXISTS name TEXT,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS facility_type TEXT,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active',
ADD COLUMN IF NOT EXISTS square_footage NUMERIC,
ADD COLUMN IF NOT EXISTS facility_condition_index NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS created_by UUID,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Ensure buildings table has all columns
ALTER TABLE buildings 
ADD COLUMN IF NOT EXISTS facility_id UUID REFERENCES facilities(id),
ADD COLUMN IF NOT EXISTS name TEXT,
ADD COLUMN IF NOT EXISTS building_number TEXT,
ADD COLUMN IF NOT EXISTS building_type TEXT,
ADD COLUMN IF NOT EXISTS construction_date DATE,
ADD COLUMN IF NOT EXISTS square_footage NUMERIC,
ADD COLUMN IF NOT EXISTS number_of_rooms INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active',
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS created_by UUID,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_facilities_status ON facilities(status);
CREATE INDEX IF NOT EXISTS idx_buildings_facility_id ON buildings(facility_id);
CREATE INDEX IF NOT EXISTS idx_buildings_status ON buildings(status);

-- Disable RLS for testing
ALTER TABLE facilities DISABLE ROW LEVEL SECURITY;
ALTER TABLE buildings DISABLE ROW LEVEL SECURITY; 